=== netspective/physia-2001/HealthSuite/Database/schema-physia-src/schema-markup.dtd
<!-- ** BASIC DATA DICTIONARY ******************************************** -->

<!ENTITY % DATATYPE.TEXT "(#PCDATA)">
<!ENTITY % DATATYPE.INTEGER "(#PCDATA)">
<!ENTITY % DATATYPE.ENUM "(#PCDATA)">
<!ENTITY % DATATYPE.BOOLEAN "(yes | no)">

<!-- ********************************************************************* -->

<!ELEMENT schema (datatype | tabletype | include | table | data)+>
	<!ATTLIST schema name CDATA #REQUIRED>

	<!ELEMENT datatype (description?, (sqldefn | composite)?, sqlwritefmt?, dbmscustom?, size?, transform*, validate*, default?, cache*, table*)>
		<!ATTLIST datatype name CDATA #REQUIRED>
		<!ATTLIST datatype type CDATA #IMPLIED>
		<!ATTLIST datatype parentref CDATA #IMPLIED>
		<!ATTLIST datatype selfref CDATA #IMPLIED>
		<!ATTLIST datatype lookupref CDATA #IMPLIED>
		<!ATTLIST datatype required (yes | no | dbms) "no">
		<!ATTLIST datatype calc (no | trigger) "no">
		<!ATTLIST datatype unique %DATATYPE.BOOLEAN; "no">
		<!ATTLIST datatype indexed (yes | no | bitmap) "no">
		<!ATTLIST datatype primarykey %DATATYPE.BOOLEAN; "no">
		<!ATTLIST datatype group CDATA #IMPLIED> <!-- DEPRECATED -->
		<!ATTLIST datatype abbrev CDATA #IMPLIED>
		<!ATTLIST datatype sqldefn CDATA #IMPLIED>
		<!ATTLIST datatype sqlwritefmt CDATA #IMPLIED>
		<!ATTLIST datatype size CDATA #IMPLIED>
		<!ATTLIST datatype default CDATA #IMPLIED>
		<!ATTLIST datatype cache CDATA #IMPLIED>
		<!ATTLIST datatype textsearch CDATA #IMPLIED> <!-- NEEDS TO BE IMPLEMENTED -->
		<!ELEMENT sqldefn %DATATYPE.TEXT;>
		<!ELEMENT sqlwritefmt %DATATYPE.TEXT;>
		<!ELEMENT composite (column)+>
		<!ELEMENT size %DATATYPE.INTEGER;>
		<!ELEMENT default %DATATYPE.TEXT;>
		<!ELEMENT cache %DATATYPE.TEXT;>
		<!ELEMENT dbmscustom (oracle)+>
			<!ELEMENT oracle (ctldatatype)>
				<!ELEMENT ctldatatype %DATATYPE.TEXT;>

	<!ELEMENT include EMPTY>
		<!ATTLIST include file CDATA #REQUIRED>
		<!ATTLIST include ifdefined CDATA #IMPLIED>
		<!ATTLIST include ifnotdefined CDATA #IMPLIED>

	<!ELEMENT tabletype (description?, parent?, param*, column*, data?, enum*)>
		<!ATTLIST tabletype name CDATA #REQUIRED>
		<!ATTLIST tabletype abbrev CDATA #IMPLIED>
		<!ATTLIST tabletype type CDATA #IMPLIED>
		<!ATTLIST tabletype parent CDATA #IMPLIED>
		<!ATTLIST tabletype group CDATA #IMPLIED> <!-- DEPRECATED -->
		<!ELEMENT parent %DATATYPE.TEXT;>
		<!ELEMENT param %DATATYPE.TEXT;>
			<!ATTLIST param name CDATA #REQUIRED>

	<!ELEMENT table (description?, parent?, param*, column*, data?, enum*)>
		<!ATTLIST table name CDATA #REQUIRED>
		<!ATTLIST table abbrev CDATA #IMPLIED>
		<!ATTLIST table type CDATA #IMPLIED>
		<!ATTLIST table parent CDATA #IMPLIED>
		<!ATTLIST table group CDATA #IMPLIED> <!-- DEPRECATED -->

	<!ELEMENT column (description?, transform*, validate*, dbmscustom?, cache*, table*)>
		<!ATTLIST column name CDATA #REQUIRED>
		<!ATTLIST column type CDATA "text">
		<!ATTLIST column parentref CDATA #IMPLIED>
		<!ATTLIST column selfref CDATA #IMPLIED>
		<!ATTLIST column lookupref CDATA #IMPLIED>
		<!ATTLIST column size CDATA #IMPLIED>
		<!ATTLIST column primarykey %DATATYPE.BOOLEAN; "no">
		<!ATTLIST column required (yes | no | dbms) "no">
		<!ATTLIST column calc (no | trigger) "no">
		<!ATTLIST column unique %DATATYPE.BOOLEAN; "no">
		<!ATTLIST column uniquegrp CDATA #IMPLIED>
		<!ATTLIST column uniquegrppos CDATA #IMPLIED> <!-- NEEDS TO BE IMPLEMENTED -->
		<!ATTLIST column indexed (yes | no | bitmap) "no">
		<!ATTLIST column indexgrp CDATA #IMPLIED>
		<!ATTLIST column indexgrppos CDATA #IMPLIED> <!-- NEEDS TO BE IMPLEMENTED -->
		<!ATTLIST column descr CDATA #IMPLIED>
		<!ATTLIST column default CDATA #IMPLIED>
		<!ATTLIST column group CDATA #IMPLIED> <!-- DEPRECATED -->
		<!ATTLIST column abbrev CDATA #IMPLIED>
		<!ATTLIST column cache CDATA #IMPLIED>
		<!ATTLIST column caption CDATA #IMPLIED> <!-- DEPRECATED -->
		<!ATTLIST column textsearch CDATA #IMPLIED> <!-- NEEDS TO BE IMPLEMENTED -->

	<!ELEMENT description %DATATYPE.TEXT;>

	<!ELEMENT validate %DATATYPE.TEXT;> <!-- NOT IMPLEMENTED -- NEED? -->
		<!ATTLIST validate method (constraint | trigger) #REQUIRED>
		<!ATTLIST validate type (numset | numrange | textset) #REQUIRED>
		<!ATTLIST validate set CDATA #REQUIRED>
		<!ATTLIST validate setdelim CDATA ",">

	<!ELEMENT transform %DATATYPE.TEXT;> <!-- NOT IMPLEMENTED -- NEED? -->
		<!ATTLIST transform method (uppercase | lowercase) #REQUIRED>

	<!ELEMENT data (import | row | enum | delimrow | delimrows)*>
		<!ATTLIST data table CDATA #IMPLIED>  <!-- needed only when self-standing (not inside table) -->
		<!ATTLIST data delim CDATA ",">
		<!ATTLIST data blanks (keep | ignore | null) "ignore">
		<!ELEMENT import EMPTY>
			<!ATTLIST import method (load) #REQUIRED>
			<!ATTLIST import src CDATA #REQUIRED>
		<!ELEMENT delimrow %DATATYPE.TEXT;>
		<!ELEMENT delimrows %DATATYPE.TEXT;>
		<!ELEMENT row (col)*>
			<!ELEMENT col %DATATYPE.TEXT;>
				<!ATTLIST col name CDATA #IMPLIED>
		<!ELEMENT enum %DATATYPE.TEXT;>
			<!ATTLIST enum id CDATA #IMPLIED>
			<!ATTLIST enum abbrev CDATA #IMPLIED>

=== netspective/physia-2001/HealthSuite/Database/schema-physia-src/generic-datatypes.xml
<?xml version="1.0"?>
<!DOCTYPE schema SYSTEM "schema-markup.dtd">

<schema name="generic-datatypes.xml">
	<datatype name="text">
		<sqldefn>varchar2(%size%)</sqldefn>
		<sqlwritefmt>'$escapedTextValue$'</sqlwritefmt>
		<size>32</size>
	</datatype>

	<datatype name="char">
		<sqldefn>char(1)</sqldefn>
		<sqlwritefmt>'$escapedTextValue$'</sqlwritefmt>
	</datatype>

	<datatype name="user_id" type="text">
		<sqlwritefmt>'$escapedTextValue$'</sqlwritefmt>
		<size>32</size>
	</datatype>

	<datatype name="float">
		<sqldefn>number(20,6)</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
	</datatype>

	<datatype name="integer">
		<sqldefn>number(8)</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
	</datatype>

	<datatype name="smallint">
		<sqldefn>number(4)</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
	</datatype>

	<datatype name="longint">
		<sqldefn>number(16)</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
	</datatype>

	<datatype name="bitmaskedflags">
		<sqldefn>number(16)</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
	</datatype>

	<datatype name="boolean">
		<sqldefn>number(1)</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
		<validate method="constraint" type="numset" set="0,1"/>
	</datatype>

	<datatype name="currency">
		<sqldefn>number(12,2)</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
	</datatype>

	<datatype name="percentage">
		<sqldefn>number(5,2)</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
	</datatype>

	<datatype name="lookup">
		<sqldefn>number(8)</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
	</datatype>

	<datatype name="date">
		<sqldefn>date</sqldefn>
		<sqlwritefmt>to_date('$value$', 'MM/DD/YYYY')</sqlwritefmt>
	</datatype>

	<datatype name="stamp">
		<sqldefn>date</sqldefn>
		<sqlwritefmt>to_date('$value$', 'MM/DD/YYYY HH:MI AM')</sqlwritefmt>
	</datatype>

	<datatype name="time">
		<sqldefn>date</sqldefn>
		<sqlwritefmt>to_date('$value$', 'HH:MI AM') + #session.GMT_DAYOFFSET# </sqlwritefmt>
	</datatype>

	<datatype name="socsec" type="text" size="11"/>
	<datatype name="password" type="text" size="16"/>

	<datatype name="autoinc">
		<sqldefn>number(16)</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
		<copytype>longint</copytype>
	</datatype>

	<datatype name="datablock">
		<sqldefn>clob</sqldefn>
		<sqlwritefmt>$value$</sqlwritefmt>
	</datatype>

	<datatype name="version_id" type="autoinc"/>

	<datatype name="md5key" type="text" size="32"/>

	<table name="Reference_Item">
		<description>
			This table is basically used for creating parent/child relationships
			for Enumeration and Lookup tables. Since it has no columns, no physical
			table will exist so it becomes a simple logical placeholder.
		</description>
	</table>

	<tabletype name="Enumeration" parent="Reference_Item">
		<param name="capsize">64</param>
		<param name="abbrevsize">32</param>

		<column name="id" type="integer" primarykey="yes" descr="The value associated with a single enum"/>
		<column name="caption" type="text" size="$capsize$" required="yes" descr="The name/text an end-user would see"/>
		<column name="abbrev" type="text" size="$abbrevsize$" unique="yes" descr="An abbreviated form of the caption"/>
	</tabletype>

	<table name="Lookup_Result_Type" abbrev="LkResTy" type="Enumeration">
		<enum>ID</enum>
		<enum>Caption</enum>
		<enum>Abbreviation</enum>
	</table>

	<tabletype name="Lookup" type="Enumeration">
		<column name="group_name" type="text" size="32" descr="The group to which the lookup item belongs"/>
		<column name="sort_seq" type="integer" descr="The sorting sequence within the group (if sorting differently than the ID or Caption"/>
		<column name="result" lookupref="Lookup_Result_Type" descr="The type of result after a lookup (the value that should be used for the lookup -- the id or caption or abbreviation)"/>
	</tabletype>

	<tabletype name="Org_Lookup" type="Lookup">
		<column name="org_internal_id" lookupref="Org.org_internal_id" descr="The organization that owns this item (NULL if owned globally)"/>
	</tabletype>

	<tabletype name="Type_Definition" type="Lookup">
		<column name="remarks" type="text" size="2048" descr="Any special remarks, usage instructions etc."/>
	</tabletype>

	<datatype name="text_set" type="text" size="255">
		<table name="$parenttbl_name$_$parentcol_Name$" abbrev="$parenttbl_abbrev$$parentcol_Short$SM">
			<description>
				This table is a cache of its parent's text_set column. The contents
				of this table are updated automatically via a trigger.
				DO NOT INSERT/UPDATE/DELETE MANUALLY.

				The "set" type column in the main table is actually a cache of all
				the set members in the child table. A set is limited to about 20-25
				10-character member names. The column in the main table is a comma-
				separated list of text items. The child table is the exact same contents
				in a row-oriented format in a separate table (maintained by triggers).
			</description>
			<parent>$parenttbl_name$</parent>
			<column name="parent_id" usetype="$parenttbl_name$.$parenttbl_prikey$" primarykey="yes" descr="The owner of the set member (this SHOULD be a foreign key, but causes a mutating trigger problem)"/>
			<column name="member_name" primarykey="yes" type="text" size="32" cache="extract:$parenttbl_name$.$parentcol_name$" descr="The set member name"/>
		</table>
		<assert check="parentTblHasSinglePrimaryKey"/>
		<templateflag name="addtriggers" value="text_set"/>
	</datatype>

	<datatype name="lookup_set" type="text" size="255">
		<table name="$parenttbl_name$_$parentcol_Name$" abbrev="$parenttbl_abbrev$$parentcol_Short$SM">
			<description>
				This table is a cache of its parent's lookup_set column. The contents
				of this table are updated automatically via a trigger.
				DO NOT INSERT/UPDATE/DELETE MANUALLY.

				The "set" type column in the main table is actually a cache of all
				the set members in the child table. The column in the main table is a comma-
				separated list of text items. The child table is the exact same contents
				in a row-oriented format in a separate table (maintained by triggers).
			</description>
			<parent>$parenttbl_name$</parent>
			<column name="parent_id" usetype="$parenttbl_name$.$parenttbl_prikey$" primarykey="yes" descr="The owner of the set member (this SHOULD be a foreign key, but causes a mutating trigger problem)"/>
			<column name="member_name" primarykey="yes" lookupref="$parentcol.lookupsetref$" cache="extract:$parenttbl_name$.$parentcol_name$" descr="The set member ID"/>
		</table>
		<assert check="parentTblHasSinglePrimaryKey"/>
		<templateflag name="addtriggers" value="lookup_set"/>
	</datatype>

</schema>

=== netspective/physia-2001/HealthSuite/Database/schema-physia-src/organization.xml
<?xml version="1.0"?>
<!DOCTYPE schema SYSTEM "schema-markup.dtd">

<schema name="organization">
	<include file="generic-datatypes.xml"/>	
	<table name="Org_Association" abbrev="OrgAn" type="Audit,Secure">
		<description>Associations between Organization</description>
		<column name="org_assn_id" type="autoinc" primarykey="yes" descr="Unique Association ID"/>
		<column name="org_assn_status" lookupref="Org_Association_Status" indexed="yes" descr="Whether or not association is currently active"/>
		<column name="org_assn_type" lookupref="Org_Association_Type" indexed="yes" required="yes" descr="Type of association"/>
		<column name="org_assn_sequence" type="integer" indexed="yes" descr="If there is more than one association, this is the sequence"/>
		<column name="org_internal_id" parentref="org.org_internal_id" indexed="yes" required="yes" descr="Organization ID"/>
		<column name="assn_org_internal_id" lookupref="org.org_internal_id" indexed="yes" descr="Associated Organization ID"/>
	</table>
	<table name="Org_Association_Status" abbrev="OrgAsnSt" type="Enumeration">
		<description>Variety of associations that a document can have to another document.</description>
		<enum id="0">Active</enum>
		<enum id="1">Inactive</enum>
	</table>		
	<table name="Org_Association_Type" abbrev="OrgAsnTy" type="Enumeration">
		<description>Types of assocations between two Orgs</description>
		<enum id="0">None</enum>
		<enum id="1">Self</enum>		
		<enum id="2">Parent Organization</enum>
		<enum id="3">Child Organization</enum>
		<enum id="100">IPA</enum>
		<enum id="110">IPA Member</enum>
	</table>	
</schema>

=== netspective/physia-2001/HealthSuite/Database/schema-physia-src/person.xml
<?xml version="1.0"?>
<!DOCTYPE schema SYSTEM "schema-markup.dtd">

<schema name="person">
	<include file="generic-datatypes.xml"/>

	<table name="Person_Referral_Note" abbrev="RefNote" type="Audit,Secure">
		<description>Notes associated with a referral</description>
		<column name="referral_note_id" abbrev="refNteId" type="autoinc" primarykey="yes" descr="Unique Referral Note ID"/>		
		<column name="referral_id" parentref="Person_Referral.referral_id"  descr="Referral ID of referral notes belongs"/>				
		<column name="person_id"  lookupref="Person.person_id" descr="Person ID of person creating the note"/>
		<column name="note"  type="text" size="1024" descr="Referral Note"/>		
		<column name="note_date"  type="stamp" descr="Date Of Note was taken"/>			
		<column name="org_internal_id"  lookupref="org.org_internal_id" abbrev="insOrgIntId" descr="Org Interal ID of Main org note belongs"/>				
	</table>
	
	<table name="Person_Referral" abbrev="PerRef" type="Audit,Secure">
		<description></description>
		<column name="referral_id" type="autoinc" primarykey="yes" descr="Unique Referral ID"/>
		<column name="request_date" type="stamp" descr="Date of Request"/>
		<column name="referral_urgency" lookupref="Referral_Urgency.id" descr="Referral Urgency"/>
		<column name="user_id"  parentref="Person.person_id" descr="Person who has created this referral or to whom this referral is transferred"/>
		<column name="person_id"  parentref="Person.person_id" descr="Person ID of patient"/>
		<column name="requester_id" parentref="Person.person_id" descr="Person ID of Requesting Physician"/>
		<column name="product_internal_id" lookupref="Insurance.ins_internal_id"  abbrev="prdIntId" descr="Insurance Product Internal ID"/>
		<column name="ins_org_internal_id" lookupref="org.org_internal_id" abbrev="insOrgIntId" descr="Insurance Company Org Internal"/>
		<column name="code"  type="text" size="60" descr="Usually a CPT code or code for the service/product"/>
		<column name="code_type"  lookupref="Catalog_Entry_Type" descr="Code types such as cpt, hcpcs, etc"/>
		<column name="rel_diags"  abbrev="rd" type="text_set" descr="Related diagnosis codes (comma-separated)"/>
		<column name="provider_id" parentref="Person.person_id" descr="Person ID of Physician Patient will be referred"/>
		<column name="speciality"  type="text" size="512" descr="Speciality of referred Physician"/>
		<column name="referral_type" lookupref="Referral_Type.id" type="duration" descr="Type of Referral"/>
		<column name="allowed_visits" type="integer"  descr="Number of Visits allowed"/>
		<column name="auth_number" type="text" size="60" descr="Authorization Number"/>
		<column name="referral"  type="duration" descr=""/>
		<column name="communication" lookupref="Referral_Communication.id" type="duration" descr="Method of communication"/>
		<column name="completion_date"  type="stamp" descr="Date Of Completion"/>
		<column name="recheck_date"  type="stamp" descr="Recheck Date"/>
		<column name="referral_status"  lookupref="Referral_Status.id" descr="Status of Referral"/>
		<column name="referral_status_date"  type="stamp" descr="Status of Referral"/>
		<column name="referral_reason"  type="text" size="512" descr="Short description for annotating the reason"/>
		<column name="comments"  type="text" size="512" descr="Referral comments"/>
	</table>

	<table name="Referral_Communication" abbrev="RefComm" type="Enumeration">
		<description>Referral Communication method</description>
		<enum id="0">Verbal</enum>
		<enum id="1">Fax</enum>
		<enum id="2">E-Mail</enum>
		<enum id="3">Mail</enum>
		<enum id="4">Left Message</enum>
	</table>

	<table name="Referral_Urgency" abbrev="RefUrge" type="Enumeration">
		<description>Referral Urgency</description>
		<enum id="0">Stat</enum>
		<enum id="1">Regular</enum>
		<enum id="2">Follow Up</enum>
	</table>

	<table name="Referral_Status" abbrev="RefSts" type="Enumeration">
		<description>Referral Type</description>
		<enum id="0">Active</enum>
		<enum id="1">Inactive</enum>
		<enum id="2">Transferred</enum>
		<enum id="3">Closed</enum>
	</table>

	<table name="Referral_Type" abbrev="RefType" type="Enumeration">
		<description>Referral Type</description>
		<enum id="0">Test</enum>
		<enum id="1">Consultation</enum>
		<enum id="2">Evaluation</enum>
		<enum id="3">Treatment</enum>
		<enum id="4">Surgery</enum>
		<enum id="5">Procedure</enum>
	</table>


</schema>

=== netspective/physia-2001/web-aspire/Database/schema-src/devices.xml
<?xml version="1.0"?>
<!DOCTYPE schema SYSTEM "schema-markup.dtd">

<schema name="typedef-properties">
	<include file="generic-datatypes.xml"/>

	<table name="Document_Type" abbrev="DocTy" type="Enumeration">
		<enum>Superbill</enum>
		<enum>Claim</enum>
		<enum>Face Sheet</enum>
	</table>
	
	<table name="Device_Type" abbrev="DevTy" type="Enumeration">
		<enum>Printer</enum>
	</table>
	
	<table name="Device_Specification" abbrev="DevSpec">
		<description>List of Devices</description>
		<column name="device_id" type="autoinc" primarykey="yes" descr="Unique Device ID"/>
		<column name="device_type" lookupref="Device_Type" descr="Device Type, look in Device_Type table"/>
		<column name="host_name" type="text" size="128" descr="The hostname of the computer this device is connected to."/>
		<column name="device_name" type="text" size="128" descr="The name this device is referred to as."/>
		<column name="device_descr" type="text" size="256" descr="Device manufacturer, model etc"/>
		<column name="device_location" type="text" size="256" descr="Physical device location"/>
		<data>
			<row>
				<col name="device_id">0</col>
				<col name="device_type">0</col>
				<col name="host_name">63.96.146.118</col>
				<col name="device_name">oki</col>
				<col name="device_descr">OKI Microline 390 Turbo</col>
				<col name="device_location">Attached to Titanium</col>
			</row>
			<row>
				<col name="device_id">1</col>
				<col name="device_type">0</col>
				<col name="host_name">63.96.146.118</col>
				<col name="device_name">mercury</col>
				<col name="device_descr">HP Laserjet 4050 PS</col>
				<col name="device_location">Physia TQ - Next to conference room</col>
			</row>
			<row>
				<col name="device_id">2</col>
				<col name="device_type">0</col>
				<col name="host_name">204.2.61.253</col>
				<col name="device_name">houstonLaser</col>
				<col name="device_descr">HP Laserjet 4050 PS</col>
				<col name="device_location">Physia HQ - Location Unknown</col>
			</row>
			<row>
				<col name="device_id">3</col>
				<col name="device_type">0</col>
				<col name="host_name">204.2.61.253</col>
				<col name="device_name">houstonOKI</col>
				<col name="device_descr">OKI Microline 390 Turbo</col>
				<col name="device_location">Physia HQ - Location Unknown</col>
			</row>
		</data>
	</table>

	<table name="Device_Attribute" abbrev="DevAttr" type="Attribute">
		<param name="parentref">Device_Specification.device_id</param>
	</table>
	
	<table name="Device_Association" abbrev="DevAssoc">
		<description>Device Associations with Orgs and People</description>
		<column name="device_assoc_id" type="autoinc" descr="Unique Device Association ID"/>
		<column name="device_id" lookupref="Device_Specification.device_id" descr="The unique device ID for this device"/>
		<column name="org_internal_id" lookupref="Org.org_internal_id" descr="The organization id to associate this device with"/>
		<column name="document_type" lookupref="Document_Type" descr="The document type to associate this device with"/>
		<column name="person_id" lookupref="Person.person_id" descr="The person to assocaite this device with"/>
		<data>
			<row>
				<col name="device_assoc_id">0</col>
				<col name="device_id">0</col>
				<col name="org_internal_id">1</col>
				<col name="document_type">0</col>
				<col name="person_id">SJONES</col>
			</row>
			<row>
				<col name="device_assoc_id">1</col>
				<col name="device_id">1</col>
				<col name="org_internal_id">1</col>
				<col name="document_type">NULL</col>
				<col name="person_id">NULL</col>
			</row>
			<row>
				<col name="device_assoc_id">2</col>
				<col name="device_id">2</col>
				<col name="org_internal_id">1</col>
				<col name="document_type">NULL</col>
				<col name="person_id">SJONES</col>
			</row>
			<row>
				<col name="device_assoc_id">3</col>
				<col name="device_id">3</col>
				<col name="org_internal_id">1</col>
				<col name="document_type">0</col>
				<col name="person_id">NULL</col>
			</row>
		</data>
	</table>
	
</schema>

=== netspective/physia-2001/HealthSuite/Database/schema-physia-src/org_person.xml
<?xml version="1.0"?>
<!DOCTYPE schema SYSTEM "schema-markup.dtd">
<schema name="org_person">

        <table name="Org" type="Audit,Secure,Restrict_Rows">
                <description>An organization, such as a physician's private practice, a hospital, or an insurance company</description>
                <column name="org_internal_id" type="autoinc" primarykey="yes" descr="Unique organization record identification (in entire system) for internal use"/>
                <column name="owner_org_id" selfref="org.org_internal_id" uniquegrp="orgid" descr="ID for owner(creator) of organization"/>
                <column name="org_id" required="yes" type="entity_id" uniquegrp="orgid" descr="Unique org identification within owner organization."/>
                <column name="parent_org_id" selfref="org.org_internal_id" indexed="yes" descr="ID for parent organization"/>
                <column name="category" type="text_set" descr="Type(s) of organization [comma-separated if more than one]"/>
                <column name="tax_id" type="text" descr="Tax ID"/>
                <column name="name_primary" type="text" size="128" descr="Name of organization" required="yes"/>
                <column name="name_trade" type="text" size="128" descr="Trade name of organization"/>
                <column name="time_zone" type="text" size="10" descr="Time zone that the organization operates in"/>
                <data>
                        <row>
                                <col name="org_internal_id">1</col>
                                <col name="cr_stamp">12/24/2011</col>
                                <col name="version_id">11</col>
                                <col name="org_id">abc123</col>
                                <col name="name_primary">xyz789</col>
                        </row>
                </data>

        </table>

        <table name="Person" abbrev="Per" type="Audit,Secure,Restrict_Rows">
                <description>A person, such as a doctor, a nurse, a receptionist, or a patient</description>
                <!-- column name="person_internal_id" type="autoinc" primarykey="yes" descr="Unique person record identification (in entire 
system) for internal use"/ -->
                <column name="person_id" primarykey="yes" type="entity_id" descr="Unique ID for a person within an organization."/>
                <column name="person_ref" type="text" size="32" descr="A reference account number/id (in the user's system)"/>                <column name="ssn" type="socsec" descr="Social Security number"/>
                <column name="name_prefix" type="text" size="16"/>
                <column name="name_first" type="text" required="yes" size="32"/>
                <column name="name_middle" type="text" size="32"/>
                <column name="name_last" type="text" required="yes" size="32"/>
                <column name="name_suffix" type="text" size="16"/>
                <column name="short_name" type="text" calc="trigger" size="42" descr="[first letter of name_first] [name_last]"/>
                <column name="simple_name" type="text" calc="trigger" size="96" descr="[name_first] [name_last]"/>
                <column name="complete_name" type="text" calc="trigger" size="128" descr="[name_prefix] [name_first] [name_middle] [name_last] [name_suffix]"/>
                <column name="short_sortable_name" type="text" calc="trigger" size="42" descr="[name_last], [first letter of name_first]"/>
                <column name="complete_sortable_name" type="text" calc="trigger" size="128" descr="[name_last], [name_first] [name_middle]" />
                <column name="gender" lookupref="Gender" default="0" descr="Gender"/>
                <column name="marital_status" lookupref="Marital_Status" default="0" descr="Marital status"/>
                <column name="date_of_birth" type="date" descr="Date of Birth"/>
                <column name="age" type="integer" descr="Actual age (only required if date_of_birth is NULL or not known)"/>
                <column name="ethnicity" type="text_set" descr="The primary/secondary ethnicity or race [comma-separated if more than one]"/>
                <column name="language" type="text_set" descr="Language(s) a person speaks [comma-separated if more than one]"/>
                <column name="language2" type="lookup_set" lookupsetref="Gender" descr="Language(s) a person speaks [comma-separated if more than one]"/>
                <column name="login_type" lookupref="Login_Type" descr="The login information for this person">
                        <table name="$parenttbl_name$_Login" abbrev="$parenttbl_abbrev$Lgi" type="Audit,Secure">
                                <column name="person_id" parentref="$parenttbl_name$.$parenttbl_prikey$" uniquegrp="orgperson" indexed="yes" descr="The person for whom login information is specified"/>
                                <column name="org_internal_id" lookupref="Org.org_internal_id" indexed="yes" uniquegrp="orgperson" descr="The organization for which login information is supplied"/>
                                <column name="password" type="text" size="16" descr="The login password"/>
                                <column name="quantity" type="integer" default="1" descr="The number of times login is allowed from different sessions"/>
                       </table>
                </column>

                 <data>
                        <row>
                                <col name="person_id">SJONES</col>
                                <col name="cr_stamp">11/13/2011</col>
                                <col name="cr_org_internal_id">11</col>
                                <col name="name_first">JONES</col>
                                <col name="name_last">STEVE</col>
                        </row>
 
                        <row>
                                <col name="person_id">NULL</col>
                                <col name="cr_stamp">11/23/2011</col>
                                <col name="cr_org_internal_id">21</col>
                                <col name="name_first">JONESA</col>
                                <col name="name_last">STEVEN</col>
                       </row>
                </data>

        </table>
</schema>
