=== netspective/physia-2001/HealthSuite/Database/schema-physia-src/schema-markup.dtd
<!-- ** BASIC DATA DICTIONARY ******************************************** -->

<!ENTITY % DATATYPE.TEXT "(#PCDATA)">
<!ENTITY % DATATYPE.INTEGER "(#PCDATA)">
<!ENTITY % DATATYPE.ENUM "(#PCDATA)">
<!ENTITY % DATATYPE.BOOLEAN "(yes | no)">

<!-- ********************************************************************* -->

<!ELEMENT schema (datatype | tabletype | include | table | data)+>
	<!ATTLIST schema name CDATA #REQUIRED>

	<!ELEMENT datatype (description?, (sqldefn | composite)?, sqlwritefmt?, dbmscustom?, size?, transform*, validate*, default?, cache*, table*)>
		<!ATTLIST datatype name CDATA #REQUIRED>
		<!ATTLIST datatype type CDATA #IMPLIED>
		<!ATTLIST datatype parentref CDATA #IMPLIED>
		<!ATTLIST datatype selfref CDATA #IMPLIED>
		<!ATTLIST datatype lookupref CDATA #IMPLIED>
		<!ATTLIST datatype required (yes | no | dbms) "no">
		<!ATTLIST datatype calc (no | trigger) "no">
		<!ATTLIST datatype unique %DATATYPE.BOOLEAN; "no">
		<!ATTLIST datatype indexed (yes | no | bitmap) "no">
		<!ATTLIST datatype primarykey %DATATYPE.BOOLEAN; "no">
		<!ATTLIST datatype group CDATA #IMPLIED> <!-- DEPRECATED -->
		<!ATTLIST datatype abbrev CDATA #IMPLIED>
		<!ATTLIST datatype sqldefn CDATA #IMPLIED>
		<!ATTLIST datatype sqlwritefmt CDATA #IMPLIED>
		<!ATTLIST datatype size CDATA #IMPLIED>
		<!ATTLIST datatype default CDATA #IMPLIED>
		<!ATTLIST datatype cache CDATA #IMPLIED>
		<!ATTLIST datatype textsearch CDATA #IMPLIED> <!-- NEEDS TO BE IMPLEMENTED -->
		<!ELEMENT sqldefn %DATATYPE.TEXT;>
		<!ELEMENT sqlwritefmt %DATATYPE.TEXT;>
		<!ELEMENT composite (column)+>
		<!ELEMENT size %DATATYPE.INTEGER;>
		<!ELEMENT default %DATATYPE.TEXT;>
		<!ELEMENT cache %DATATYPE.TEXT;>
		<!ELEMENT dbmscustom (oracle)+>
			<!ELEMENT oracle (ctldatatype)>
				<!ELEMENT ctldatatype %DATATYPE.TEXT;>

	<!ELEMENT include EMPTY>
		<!ATTLIST include file CDATA #REQUIRED>
		<!ATTLIST include ifdefined CDATA #IMPLIED>
		<!ATTLIST include ifnotdefined CDATA #IMPLIED>

	<!ELEMENT tabletype (description?, parent?, param*, column*, data?, enum*)>
		<!ATTLIST tabletype name CDATA #REQUIRED>
		<!ATTLIST tabletype abbrev CDATA #IMPLIED>
		<!ATTLIST tabletype type CDATA #IMPLIED>
		<!ATTLIST tabletype parent CDATA #IMPLIED>
		<!ATTLIST tabletype group CDATA #IMPLIED> <!-- DEPRECATED -->
		<!ELEMENT parent %DATATYPE.TEXT;>
		<!ELEMENT param %DATATYPE.TEXT;>
			<!ATTLIST param name CDATA #REQUIRED>

	<!ELEMENT table (description?, parent?, param*, column*, data?, enum*)>
		<!ATTLIST table name CDATA #REQUIRED>
		<!ATTLIST table abbrev CDATA #IMPLIED>
		<!ATTLIST table type CDATA #IMPLIED>
		<!ATTLIST table parent CDATA #IMPLIED>
		<!ATTLIST table group CDATA #IMPLIED> <!-- DEPRECATED -->

	<!ELEMENT column (description?, transform*, validate*, dbmscustom?, cache*, table*)>
		<!ATTLIST column name CDATA #REQUIRED>
		<!ATTLIST column type CDATA "text">
		<!ATTLIST column parentref CDATA #IMPLIED>
		<!ATTLIST column selfref CDATA #IMPLIED>
		<!ATTLIST column lookupref CDATA #IMPLIED>
		<!ATTLIST column size CDATA #IMPLIED>
		<!ATTLIST column primarykey %DATATYPE.BOOLEAN; "no">
		<!ATTLIST column required (yes | no | dbms) "no">
		<!ATTLIST column calc (no | trigger) "no">
		<!ATTLIST column unique %DATATYPE.BOOLEAN; "no">
		<!ATTLIST column uniquegrp CDATA #IMPLIED>
		<!ATTLIST column uniquegrppos CDATA #IMPLIED> <!-- NEEDS TO BE IMPLEMENTED -->
		<!ATTLIST column indexed (yes | no | bitmap) "no">
		<!ATTLIST column indexgrp CDATA #IMPLIED>
		<!ATTLIST column indexgrppos CDATA #IMPLIED> <!-- NEEDS TO BE IMPLEMENTED -->
		<!ATTLIST column descr CDATA #IMPLIED>
		<!ATTLIST column default CDATA #IMPLIED>
		<!ATTLIST column group CDATA #IMPLIED> <!-- DEPRECATED -->
		<!ATTLIST column abbrev CDATA #IMPLIED>
		<!ATTLIST column cache CDATA #IMPLIED>
		<!ATTLIST column caption CDATA #IMPLIED> <!-- DEPRECATED -->
		<!ATTLIST column textsearch CDATA #IMPLIED> <!-- NEEDS TO BE IMPLEMENTED -->

	<!ELEMENT description %DATATYPE.TEXT;>

	<!ELEMENT validate %DATATYPE.TEXT;> <!-- NOT IMPLEMENTED -- NEED? -->
		<!ATTLIST validate method (constraint | trigger) #REQUIRED>
		<!ATTLIST validate type (numset | numrange | textset) #REQUIRED>
		<!ATTLIST validate set CDATA #REQUIRED>
		<!ATTLIST validate setdelim CDATA ",">

	<!ELEMENT transform %DATATYPE.TEXT;> <!-- NOT IMPLEMENTED -- NEED? -->
		<!ATTLIST transform method (uppercase | lowercase) #REQUIRED>

	<!ELEMENT data (import | row | enum | delimrow | delimrows)*>
		<!ATTLIST data table CDATA #IMPLIED>  <!-- needed only when self-standing (not inside table) -->
		<!ATTLIST data delim CDATA ",">
		<!ATTLIST data blanks (keep | ignore | null) "ignore">
		<!ELEMENT import EMPTY>
			<!ATTLIST import method (load) #REQUIRED>
			<!ATTLIST import src CDATA #REQUIRED>
		<!ELEMENT delimrow %DATATYPE.TEXT;>
		<!ELEMENT delimrows %DATATYPE.TEXT;>
		<!ELEMENT row (col)*>
			<!ELEMENT col %DATATYPE.TEXT;>
				<!ATTLIST col name CDATA #IMPLIED>
		<!ELEMENT enum %DATATYPE.TEXT;>
			<!ATTLIST enum id CDATA #IMPLIED>
			<!ATTLIST enum abbrev CDATA #IMPLIED>

=== netspective/physia-2001/HealthSuite/Database/schema-physia-src/datatypes.xml
<?xml version="1.0"?>
<!DOCTYPE schema SYSTEM "schema-markup.dtd">

<schema name="physia-datatypes">
	<include file="generic-datatypes.xml"/>
	<include file="enums.xml"/>

	<!--
	**************************************************************************
	The following datatypes are specific to physia, but general in nature
	so multiple physia applications can use them
	**************************************************************************
	-->

	<datatype name="session_id" type="text" size="16"/>
	<datatype name="entity_id" type="text" size="16"/>
	<datatype name="duration">
		<composite>
			<column name="$name$_begin_date" type="date"/>
			<column name="$name$_end_date" type="date"/>
		</composite>
	</datatype>
	<datatype name="stamp_range">
		<composite>
			<column name="$name$_begin_stamp" type="stamp"/>
			<column name="$name$_end_stamp" type="stamp"/>
		</composite>
	</datatype>
	<datatype name="entity">
		<composite>
			<column name="$name$_type" lookupref="Entity_Type"/>
			<column name="$name$_id" type="entity_id"/>
		</composite>
	</datatype>

	<tabletype name="Entity_Owned_Lookup" type="Lookup">
		<column name="parent" type="entity"/>
	</tabletype>

	<tabletype name="Entity_Owned_Type_Definition" type="Type_Definition">
		<column name="parent" type="entity"/>
	</tabletype>

	<tabletype name="Audit">
		<column name="cr_stamp" type="stamp" default="sysdate" required="dbms" group="audit" descr="Date/time record was created"/>
		<column name="cr_user_id" type="entity_id" group="audit" descr="The user that created the record"/>
		<column name="cr_org_id" type="entity_id" group="audit" descr="The org that created the record (the one the cr_user_id was logged-into)"/>
		<column name="version_id" type="version_id" required="dbms" unique="yes" group="audit" descr="A unique version number for this record (for audit purposes)"/>
	</tabletype>

	<tabletype name="Secure">
		<column name="cr_session_id" usetype="Person_Session.session_id" required="no" group="secure" descr="Session that created this record"/>
	</tabletype>

	<!--
		THE RESTRICT_ROWS AND RESTRICT_ROWS_ABBREV TableTypes ARE
		IDENTICAL EXCEPT FOR NAME OF CHILDTABLE (one has full table name + _Permit,
		the other has abbreviated table name + _Permit).
	-->

	<tabletype name="Restrict_Rows">
		<column name="permissions" lookupref="Permission_Type" descr="The permissions needed to view a specific row">
			<table name="$parenttbl_name$_Permit" abbrev="$parenttbl_abbrev$PM" type="Audit,Secure">
				<column name="parent_id" parentref="$parenttbl_name$.$parenttbl_prikey$" primarykey="yes" descr="The owner of the permission"/>
				<column name="member_type" primarykey="yes" lookupref="Permit_Member_Type" descr="The type of member that permission is being defined for (group, person, org, etc)"/>
				<column name="member_id" primarykey="yes" type="text" descr="The id of the member (a group, person, etc)"/>
				<column name="permit_flags" type="bitmaskedflags" descr="All permission booleans combined into one (for simple access)"/>
				<column name="permit_use" type="boolean" descr="Allow use of parent_id by member_id (can it be used for reporting, aggregation, etc)"/>
				<column name="permit_view" type="boolean" descr="Allow viewing of parent_id by member_id"/>
				<column name="permit_modify" type="boolean" descr="Allow modification of parent_id by member_id"/>
				<column name="permit_remove" type="boolean" descr="Allow removal of parent_id by member_id"/>
				<column name="effective" type="stamp_range" descr="Permissions are effective from start to end date (if not-NULL)"/>
				<column name="extra_data" type="text" size="512" descr="Any extra security information like applicable to zip code, county, etc"/>
			</table>
		</column>
	</tabletype>

	<tabletype name="Restrict_Rows_Abbrev">
		<column name="permissions" lookupref="Permission_Type" descr="The permissions needed to view a specific row">
			<table name="$parenttbl_abbrev$_Permit" abbrev="$parenttbl_abbrev$PM" type="Audit,Secure">
				<column name="parent_id" parentref="$parenttbl_name$.$parenttbl_prikey$" primarykey="yes" descr="The owner of the permission"/>
				<column name="member_type" primarykey="yes" lookupref="Permit_Member_Type" descr="The type of member that permission is being defined for (group, person, org, etc)"/>
				<column name="member_id" primarykey="yes" type="text" descr="The id of the member (a group, person, etc)"/>
				<column name="permit_flags" type="bitmaskedflags" descr="All permission booleans combined into one (for simple access)"/>
				<column name="permit_use" type="boolean" descr="Allow use of parent_id by member_id (can it be used for reporting, aggregation, etc)"/>
				<column name="permit_view" type="boolean" descr="Allow viewing of parent_id by member_id"/>
				<column name="permit_modify" type="boolean" descr="Allow modification of parent_id by member_id"/>
				<column name="permit_remove" type="boolean" descr="Allow removal of parent_id by member_id"/>
				<column name="effective" type="stamp_range" descr="Permissions are effective from start to end date (if not-NULL)"/>
				<column name="extra_data" type="text" size="512" descr="Any extra security information like applicable to zip code, county, etc"/>
			</table>
		</column>
	</tabletype>

	<tabletype name="Address" type="Audit,Secure">
		<description>An address of a members of a certain entity, such as a person or org.</description>
		<column name="item_id" type="autoinc" primarykey="yes" descr="Unique identifier for foreign-key and update purposes"/>
		<column name="parent_id" parentref="$parentref$" indexed="yes" uniquegrp="addrname" descr="The owner of the address"/>
		<column name="address_name" indexed="yes" type="text" size="128" uniquegrp="addrname" descr="The address name"/>
		<column name="line1" type="text" size="256" descr="The first address line"/>
		<column name="line2" type="text" size="256" descr="The second address line"/>
		<column name="city" type="text" size="128" descr="The city of the state"/>
		<column name="county" type="text" size="128" descr="The county of the state"/>
		<column name="state" type="text" size="128" descr="The state of the union"/>
		<column name="zip" type="text" size="128" descr="The postal code (+4 format)"/>
		<column name="country" type="text" size="128" descr="The country of the address"/>
		<column name="complete_addr_html" type="text" size="512" calc="trigger" descr="The complete address (created automatically)"/>
	</tabletype>

	<tabletype name="Usage">
		<description>Usage table for tracking number of reads/writes of a particular record in the parent table.</description>
		<column name="parent_id" parentref="$parentref$" indexed="yes" uniquegrp="key" descr="The owner of the usage information"/>
		<column name="person_id" lookupref="Person.person_id" indexed="yes" uniquegrp="key" descr="Specific person for which usage is being tracked"/>
		<column name="org_id" lookupref="Org.org_id" indexed="yes" uniquegrp="key" descr="Specific organization for which usage is being tracked"/>
		<column name="read_count" type="integer" descr="The number of times the parent_id has been read by person_id"/>
		<column name="write_count" type="integer" descr="The number of times the parent_id has been written by person_id"/>
	</tabletype>

	<tabletype name="Notify">
		<description>Notify table for tracking who and how to notify in case of change to a record.</description>
		<column name="parent_id" parentref="$parentref$" primarykey="yes" descr="The owner of the notification"/>
		<column name="entity" required="yes" descr="The entity that will be notified"/>
		<column name="notify_type" lookupref="Notify_Type" required="yes" descr="The type of notification being defined"/>
		<column name="notify_data" type="text" size="512" required="yes" descr="Any comments/information"/>
	</tabletype>

	<datatype name="org_text_set" type="text" size="384">
		<table name="$parenttbl_name$_$parentcol_Name$" abbrev="$parenttbl_abbrev$$parentcol_abbrev$">
			<parent>$parenttbl_name$</parent>
			<column name="parent_id" usetype="$parenttbl_name$.$parenttbl_prikey$" indexed="yes" uniquegrp="member" descr="The owner of the set member (this SHOULD be a foreign key, but causes a mutating trigger problem)"/>
			<column name="org_id" lookupref="Org.org_id" indexed="yes" uniquegrp="member" descr="Specific organization to which member belongs"/>
			<column name="member_name" indexed="yes" uniquegrp="member" type="text" size="32" cache="extract:$parenttbl_name$.$parentcol_name$" descr="The set member name"/>
		</table>
		<assert check="parentTblHasSinglePrimaryKey"/>
		<templateflag name="addtriggers" value="org_text_set"/>
	</datatype>

</schema>

=== netspective/physia-2001/HealthSuite/Database/schema-physia-src/lab_test.xml
<?xml version="1.0"?>
<!DOCTYPE schema SYSTEM "schema-markup.dtd">

<schema name="lab_test">
	<include file="generic-datatypes.xml"/>	
	
	<table name="Person_Lab_Order" abbrev="PLabOrd" type="Audit,Secure">
		<description>Contains Lab order request for a patient</description>
		<column name="lab_order_id" type="autoinc" primarykey="yes" descr="Unique Lab Order ID"/>
		<column name="person_id"  parentref="Person.person_id" indexed="yes" descr="Person ID of patient the Lab Order is created"/>	
		<column name="date_order" type="stamp"  indexed="yes"  descr="Date and Time Lab order was requested"/>			
		<column name="date_done" type="stamp" descr="Date and Time Lab order was finished"/>	
		<column name="provider_id" lookupref="person.person_id"  indexed="yes" descr="Person ID of patient the Lab Order is created"/>	
		<column name="result_id" lookupref="person.person_id"  indexed="yes" descr="Person ID of Person to contact with lab results"/>			
		<column name="lab_comments" type="text" size="512" descr="Comments to the lab"/>			
		<column name="patient_comments" type="text" size="512" descr="Comments for the patient"/>					
		<column name="instructions" type="text" size="512" descr="Instructions for the patient"/>
		<column name="icd" type="text_set"  descr="Diagnosis "/>		
		<column name="communication" lookupref="Lab_Order_Transmission.id" descr="Communication method (e-mail,fax.phone,etc) "/>				
		<column name="priority" lookupref="Lab_Order_Priority.id" descr="priority of lab request"/>						
		<column name="lab_order_status" lookupref="Lab_Order_Status.id" descr="Lab Order Status"/>								
		<column name="lab_internal_id" lookupref="Org.org_internal_id"  indexed="yes" descr="Internal ID of Lab that will perform this test"/>				
		<column name="org_internal_id" lookupref="Org.org_internal_id"  indexed="yes" descr="Internal ID of Main Org"/>						
		<column name="location_address_id" lookupref="Org_Address.item_id" descr="Address ID of Location to send Lab Order"/>						
		
	</table>	
	
	<table name="Lab_Order_Status" abbrev="LabOrdSts" type="Enumeration">
		<description>Status of Lab Order Request</description>
		<enum id="0">Approved</enum>		
		<enum id="1">Pending</enum>
		<enum id="2">Faxed to Lab</enum>		
		<enum id="3">E-Mailed to Lab</enum>				
		<enum id="4">Transmitted to Lab</enum>						
	</table>	
	
	<table name="Lab_Order_Priority" abbrev="LabOrdPri" type="Enumeration">
		<description>Priority of Lab Order Request</description>
		<enum id="0">Normal</enum>		
		<enum id="1">STAT</enum>
		<enum id="2">ASAP</enum>		
		<enum id="3">Today</enum>				
	</table>		

	<table name="Lab_Order_Transmission" abbrev="LabOrdTrans" type="Enumeration">
		<description>Priority of Lab Order Request</description>
		<enum id="0">Print</enum>		
		<enum id="1">E-Mail</enum>
		<enum id="2">Fax</enum>		
	</table>		
	
	
	<table name="Lab_Order_Entry" abbrev="LabOrdEnt" type="Audit,Secure">
		<description>Contains Lab order Entry request for a patient</description>
		<column name="entry_id" type="autoinc" primarykey="yes" descr="Unique Lab Order ID"/>
		<column name="parent_entry_id" selfref="Lab_Order_Entry.entry_id" indexed="yes" descr="If this item is a child of another item (like a group)"/>		
		<column name="parent_id" parentref="person_lab_order.lab_order_id" descr="Unique Lab Order ID"/>				
		<column name="test_entry_id" lookupref="offering_catalog_entry.entry_id" descr="Unique Lab Order ID"/>						
		<column name="options" abbrev="o" type="text_set" descr="List of options for this test"/>								
		<column name="caption" type="text" size="64" descr="The caption of the item"/>				
		<column name="lab_code" type="text" size="64" descr="The code of the item"/>								
		<column name="charge_code" type="text" size="64" descr="The code of the item"/>										
		<column name="physician_cost" type="currency" descr="The cost to physician for lab order"/>												
		<column name="patient_cost" type="currency" descr="The cost to patient for lab order"/>														
		<column name="modifier" type="text" size="64" descr="Information about order"/>														
		<column name="panel_test_name" type="text" size="512" descr="Comma seperated list of panel test names"/>
	</table>		
</schema>

=== netspective/physia-2001/HealthSuite/Database/schema-physia-src/enums.xml
<?xml version="1.0"?>
<!DOCTYPE schema SYSTEM "schema-markup.dtd">

<schema name="physia-enums">
	<include file="generic-datatypes.xml"/>

	<table name="Session_Status" abbrev="SesStat" type="Enumeration">
		<enum>Active</enum>
		<enum>Inactive (User Normal Logout)</enum>
		<enum>Inactive (User Forced Logout)</enum>
		<enum>Inactive (System Forced Logout)</enum>
		<enum>Inactive (Timeout)</enum>
	</table>

	<table name="Org_Role_Status" abbrev="RoleStat" type="Enumeration">
		<enum>Active</enum>
		<enum>Suspended</enum>
		<enum>Inactive</enum>
	</table>

	<table name="Role_Activity" abbrev="RoleActivity" type="Enumeration">
		<enum>Grant</enum>
		<enum>Revoke</enum>
	</table>

	<table name="Session_Activity_Type" abbrev="SesActv" type="Enumeration">
		<enum>Record</enum>
		<enum>Page</enum>
	</table>

	<table name="Session_Action_Type" abbrev="SesAct" type="Enumeration">
		<enum>View</enum>
		<enum>Add</enum>
		<enum>Update</enum>
		<enum>Remove</enum>
		<enum>Cancel</enum>
		<enum>NoShow</enum>
		<enum>Reschedule</enum>
		<enum>Confirm</enum>
		<enum>Verify</enum>
		<enum>Setup</enum>
		<enum>Prescribe</enum>
		<enum>Refill</enum>
		<enum>Approve</enum>
		<enum>Deny</enum>
		<enum>Submit</enum>
		<enum>Resubmit</enum>
	</table>

	<table name="Login_Type" abbrev="LgiType" type="Enumeration">
		<enum>None</enum>
		<enum>Specific (specified in Login table)</enum>
	</table>

	<table name="Entity_Type" abbrev="EntType" type="Enumeration">
		<enum>Person</enum>
		<enum abbrev="Org">Organization</enum>
		<enum abbrev="Trn">Transaction</enum>
	</table>

	<table name="Permit_Member_Type" abbrev="PermMem" type="Enumeration">
		<enum>Owner</enum>
		<enum>Person</enum>
		<enum>Organization</enum>
	</table>

	<table name="Permission_Type" abbrev="PermTyp" type="Enumeration">
		<enum>Allow All</enum>
		<enum>Allow All, Deny Some</enum>
		<enum>Deny All, Allow Some</enum>
		<enum>Allow Owner, Deny All</enum>
		<enum>Allow Owner, Deny All, Allow Some</enum>
		<enum>Allow Care Provider, Allow Owner, Deny All</enum>
		<enum>Allow Care Provider, Allow Owner, Deny All, Allow Some</enum>
		<enum>Allow Care Provider, Deny All</enum>
		<enum>Allow Care Provider, Deny All, Allow Some</enum>
		<enum>Allow Physician, Deny All</enum>
		<enum>Allow Physician, Deny All, Allow Some</enum>
		<enum id="999">No Default</enum>
	</table>

	<table name="Gender" type="Enumeration">
		<enum>Male</enum>
		<enum>Female</enum>
		<enum>Not applicable</enum>
	</table>

	<table name="Month" type="Enumeration">
		<enum>January</enum>
		<enum>February</enum>
		<enum>March</enum>
		<enum>April</enum>
		<enum>May</enum>
		<enum>June</enum>
		<enum>July</enum>
		<enum>August</enum>
		<enum>September</enum>
		<enum>October</enum>
		<enum>November</enum>
		<enum>December</enum>
	</table>

	<table name="Marital_Status" abbrev="MarStat" type="Enumeration">
		<enum>Unknown</enum>
		<enum>Single</enum>
		<enum>Married</enum>
		<enum>Partner</enum>
		<enum>Legally Separated</enum>
		<enum>Divorced</enum>
		<enum>Widowed</enum>
		<enum>Not applicable</enum>
	</table>

	<table name="Blood_Type" type="Enumeration">
		<enum>Unknown</enum>
		<enum>A+</enum>
		<enum>A-</enum>
		<enum>B+</enum>
		<enum>B-</enum>
		<enum>AB+</enum>
		<enum>AB-</enum>
		<enum>O+</enum>
		<enum>O-</enum>
	</table>

	<table name="Personal_Multibirth" abbrev="PrMtbth" type="Enumeration">
		<enum id="1">Singleton</enum>
		<enum id="2">Twin</enum>
		<enum id="3">Triplet</enum>
		<enum id="4">Quadruplet</enum>
		<enum id="5">Quintuplet</enum>
		<enum id="6">Septuplet</enum>
	</table>

	<table name="Personal_Birthorder" abbrev="PrBthOr" type="Enumeration">
		<enum id="1">First</enum>
		<enum id="2">Second</enum>
		<enum id="3">Third</enum>
		<enum id="4">Fourth</enum>
		<enum id="5">Fifth</enum>
		<enum id="6">Sixth</enum>
		<enum id="7">Seventh</enum>
		<enum id="8">Eighth</enum>
		<enum id="9">Ninth</enum>
		<enum id="10">Tenth</enum>
		<enum id="11">Eleventh</enum>
		<enum id="12">Twelvth</enum>
	</table>

	<table name="Appt_Duration" type="Enumeration">
		<enum id="10">10 minutes</enum>
		<enum id="15">15 minutes</enum>
		<enum id="20">20 minutes</enum>
		<enum id="30">30 minutes</enum>
		<enum id="45">45 minutes</enum>
		<enum id="60">1 hour</enum>
	</table>

	<table name="Deduct_Type" type="Enumeration">
		<enum>None</enum>
		<enum>Individual</enum>
		<enum>Family</enum>
		<enum>Both</enum>
	</table>

	<table name="Tax_Id_Type" type="Enumeration">
		<enum>Employer Identification Number</enum>
		<enum>Social Security Number</enum>
		<enum>Corporate Name</enum>
	</table>

	<table name="Bill_Sequence" type="Enumeration">
		<enum id="1">Primary</enum>
		<enum id="2">Secondary</enum>
		<enum id="3">Tertiary</enum>
		<enum id="4">Quaternary</enum>
		<enum id="5">Workers Comp</enum>
		<enum id="98">Terminated</enum>
		<enum id="99">InActive</enum>
	</table>

	<table name="Appt_Attendee_Type" abbrev="ApPty" type="Enumeration">
		<enum>New Patient</enum>
		<enum>Established Patient</enum>
		<enum>Temporary Patient</enum>
	</table>

	<table name="Appt_Status" abbrev="ApStat" type="Enumeration">
		<enum>Scheduled</enum>
		<enum>In Progress</enum>
		<enum>Complete</enum>
		<enum>Discard</enum>
	</table>

	<table name="Appt_Discard_Type" abbrev="ApDisc" type="Enumeration">
		<enum>Cancel</enum>
		<enum>No Show</enum>
		<enum>Patient Reschedule</enum>
		<enum>Org Reschedule</enum>
	</table>

	<table name="Trans_Related_To" abbrev="TrnRel" type="Enumeration">
		<enum>Employment</enum>
		<enum>Auto Accident</enum>
		<enum>Other Accident</enum>
	</table>

	<table name="Medication_Type" abbrev="MedType" type="Enumeration">
		<enum>Encounter</enum>
		<enum>Maintenance</enum>
		<enum>Permanent</enum>
	</table>

	<table name="Invoice_Type" type="Enumeration">
		<enum>HCFA 1500 Claim</enum>
		<enum>Services Rendered</enum>
	</table>

	<table name="Inv_Item_Type" type="Enumeration">
		<enum>Invoice</enum>
		<enum>Service</enum>
		<enum>Lab</enum>
		<enum>Co-pay</enum>
		<enum>Co-insurance</enum>
		<enum>Adjustment</enum>
		<enum>Deductible</enum>
		<enum>Void</enum>
	</table>

	<table name="Transaction_Status" type="Enumeration">
		<enum>Unknown</enum>
		<enum>Not Required</enum>
		<enum>Active</enum>
		<enum>Inactive</enum>
		<enum>Read</enum>
		<enum>Not Read</enum>
		<enum>Pending</enum>
		<enum>Filled</enum>
		<enum>Denied</enum>
	</table>

	<table name="Invoice_Status" type="Enumeration">
		<enum>Created</enum>
		<enum>Incomplete</enum>
		<enum>Pending</enum>
		<enum>On Hold</enum>
		<enum>Submitted</enum>
		<enum>Transferred</enum>
		<enum>Approved Internal</enum>
		<enum>Rejected Internal</enum>
		<enum>Electronically Transmitted to Carrier</enum>
		<enum>Transmitted to Carrier via Paper</enum>
		<enum>Approved External</enum>
		<enum>Rejected External</enum>
		<enum>Awaiting Insurance Payment</enum>
		<enum>Payments Applied</enum>
		<enum>Appealed</enum>
		<enum>Closed</enum>
		<enum>Void</enum>
		<enum>Paper Claim Printed</enum>
		<enum>Awaiting Client Payment</enum>
	</table>

	<table name="Adjust_Method" abbrev="AdjMeth" type="Enumeration">
		<enum>Payment</enum>
		<enum>Refund</enum>
		<enum>Transfer</enum>
		<enum>Auto Capitated Service Adjustment</enum>
		<enum>Transfer Balance to Next Payer</enum>
		<enum>Reverse Transfer Balance to Next Payer</enum>
		<enum>Reverse Payment Transfer</enum>
		<enum>Payment Transfer</enum>
	</table>

	<table name="Writeoff_Type" abbrev="WrOffTy" type="Enumeration">
		<enum>Discount</enum>
		<enum>Professional Courtesy</enum>
		<enum>Bad Debt</enum>
		<enum>Collection Agency</enum>
		<enum>Charity Discount</enum>
		<enum>Past File Deadline</enum>
		<enum>Posting Error</enum>
		<enum>Non-billable Service</enum>
		<enum>Returned Personal Check</enum>
		<enum>NSF Fee</enum>
		<enum>Contractual Agreement</enum>
		<enum>Transfer from Legacy System</enum>
	</table>

	<table name="Payment_Method" abbrev="PayMeth" type="Enumeration">
		<enum>Cash</enum>
		<enum>Check</enum>
		<enum>Money Order</enum>
		<enum>Debit Card</enum>
		<enum>MasterCard</enum>
		<enum>VISA</enum>
		<enum>AMEX</enum>
		<enum>Discover</enum>
		<enum>Diners Club</enum>
		<enum>Travelers Check</enum>
	</table>

	<table name="Offering_Catalog_Type" abbrev="OfCatTy" type="Enumeration">
		<enum>Fee Schedule</enum>
		<enum>Service Type</enum>
		<enum>Misc Procedure</enum>
		<enum>Contract Schedule</enum>
		<enum>Superbill</enum>
		<enum>Lab Test</enum>
	</table>

	<table name="Catalog_Entry_Status" abbrev="CatItmSt" type="Enumeration">
		<enum>Inactive</enum>
		<enum>Active</enum>
	</table>

	<table name="Catalog_Entry_Cost_Type" abbrev="CatItmCt" type="Enumeration">
		<enum>No Cost</enum>
		<enum>Specific Dollar</enum>
		<enum>Multiple of Group</enum>
		<enum>Multiple of Parent</enum>
		<enum>Medicare Value</enum>
		<enum>Multiple of RVU</enum>
		<enum>UCR 75% Value</enum>
	</table>

	<table name="Invoice_Bill_Party_Type" abbrev="BillParTy" type="Enumeration">
		<enum>Client</enum>
		<enum>Third-party Person</enum>
		<enum>Third-party Organization</enum>
		<enum>Third-party Insurance Organization</enum>
	</table>

	<table name="Survey_Item_Type" abbrev="SurItemTy" type="Enumeration">
		<enum>Question</enum>
		<enum>Statement</enum>
		<enum>Heading</enum>
		<enum>Subhead</enum>
	</table>

	<table name="Medication_Record_Type" abbrev="MedRecTy" type="Enumeration">
		<enum>Existing</enum>		
		<enum>Prescribe</enum>
		<enum>Refill</enum>
	</table>

	<table name="Insurance_Record_Type" abbrev="InsRecTy" type="Enumeration">
		<enum>Category (arbitrary grouping of other records)</enum>
		<enum>Insurance Product (child of an insurance org)</enum>
		<enum>Insurance Plan (child of an insurance product)</enum>
		<enum>Personal Coverage (optional child of insurance plan)</enum>
	</table>

	<table name="Transmission_Status" abbrev="TrnmSts" type="Enumeration">
		<enum>Transmitted</enum>
		<enum>Acknowledged</enum>
	</table>

</schema>

=== netspective/physia-2001/web-aspire/Database/schema-src/tabledata.xml
<?xml version="1.0"?>
<!DOCTYPE schema SYSTEM "schema-markup.dtd">

<schema name="physia-datadefs">

	<data table="REF_CPT">
		<import method="load" src="../refdata/cpt.txt"/>
	</data>

	<data table="REF_ICD">
		<import method="load" src="../refdata/icd.txt"/>
	</data>

	<data table="REF_Envoy_Payer">
		<import method="load" src="../refdata/envoy_payer.txt"/>
	</data>

	<data table="REF_USA_State">
		<delimrows>
			"AL","Alabama"
			"AR","Arkansas"
			"AZ","Arizona"
			"AK","Alaska"
			"CA","California"
			"CO","Colorado"
			"CT","Connecticut"
			"DE","Delaware"
			"DC","District Of Columbia"
			"FL","Florida"
			"GA","Georgia"
			"HI","Hawaii"
			"ID","Idaho"
			"IL","Illinois"
			"IN","Indiana"
			"IA","Iowa"
			"KS","Kansas"
			"KY","Kentucky"
			"LA","Louisiana"
			"ME","Maine"
			"MD","Maryland"
			"MA","Massachusetts"
			"MI","Michigan"
			"MN","Minnesota"
			"MS","Mississippi"
			"MO","Missouri"
			"MT","Montana"
			"NE","Nebraska"
			"NV","Nevada"
			"NH","New Hampshire"
			"NJ","New Jersey"
			"NM","New Mexico"
			"NY","New York"
			"NC","North Carolina"
			"ND","North Dakota"
			"OH","Ohio"
			"OK","Oklahoma"
			"OR","Oregon"
			"PA","Pennsylvania"
			"RI","Rhode Island"
			"SC","South Carolina"
			"SD","South Dakota"
			"TN","Tennessee"
			"TX","Texas"
			"UT","Utah"
			"VT","Vermont"
			"VA","Virginia"
			"WA","Washington"
			"WV","West Virginia"
			"WI","Wisconsin"
			"WY","Wyoming"
		</delimrows>
	</data>

</schema>
